#!/usr/bin/env bash
# Display PIDs and process names of processes containing "bash"
for pid in /proc/[0-9]*; do
	if grep -q "bash" "$pid/comm" 2>/dev/null; then
	   echo "PID: $(basename "$pid") - Process: $(cat "$pid/comm")"
	fi
done
